name: Test
on:
  push:
    branches:
      - main
    paths:
      - 'lib/**'
      - 'test/**'
      - 'dune-project'
      - 'comprocaml.opam'
  pull_request:
    branches:
      - main
    paths:
      - 'lib/**'
      - 'test/**'
      - 'dune-project'
      - 'comprocaml.opam'
  workflow_dispatch:
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        version:
          - '4.13'
          - '5.0'
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout tree
        uses: actions/checkout@v4

      - name: Setup OCaml
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: ${{ matrix.version }}

      - run: opam install . --deps-only --with-test

      - run: opam exec -- dune build

      - run: opam exec -- dune runtest
