name: Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
  find-changes:
    permissions:
      contents: read
      pull-requests: read
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.find-changes.outputs.targets == 'true' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36
        id: find-changes
        with:
          filters: |
            targets:
              - 'lib/**'
              - 'test/**'
              - '.github/workflows/test.yaml'

  test:
    permissions:
      contents: read
    needs: find-changes
    if: ${{ needs.find-changes.outputs.changed == 'true' }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        version:
          - '4.13'
          - '5.0'
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout tree
        uses: actions/checkout@v4

      - name: Setup OCaml
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: ${{ matrix.version }}

      - run: opam install . --deps-only --with-test

      - run: opam exec -- dune build

      - run: opam exec -- dune runtest

  # Reference:
  # - <https://stackoverflow.com/questions/70275958/how-do-i-set-a-github-branch-protection-rule-based-on-the-success-or-failure-of>
  post-test:
    runs-on: ubuntu-latest
    needs: test
    if: always()
    steps:
      - name: All tests passed
        if: ${{ !(contains(needs.*.result, 'failure')) }}
        run: exit 0

      - name: Some tests failed
        if: ${{ contains(needs.*.result, 'failure') }}
        run: exit 1
